-- AlgoLens initial schema.
-- Written in portable SQL so the same migration runs on PostgreSQL 12+ and H2 2.x.

CREATE TABLE users (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(120) NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    password_hash         VARCHAR(255) NOT NULL,
    role                  VARCHAR(32)  NOT NULL,
    credit_balance        INTEGER      NOT NULL,
    last_monthly_grant_at TIMESTAMP,
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP    NOT NULL
);

CREATE UNIQUE INDEX ux_users_email ON users (email);

CREATE TABLE problems (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug         VARCHAR(160)  NOT NULL,
    title        VARCHAR(200)  NOT NULL,
    description  VARCHAR(8000) NOT NULL,
    difficulty   VARCHAR(32)   NOT NULL,
    category     VARCHAR(64)   NOT NULL,
    language     VARCHAR(32)   NOT NULL,
    starter_code VARCHAR(100000),
    solution_code VARCHAR(100000),
    display_order INTEGER      NOT NULL,
    created_at   TIMESTAMP     NOT NULL
);

CREATE UNIQUE INDEX ux_problems_slug ON problems (slug);
CREATE INDEX ix_problems_category ON problems (category);

CREATE TABLE saved_code (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT         NOT NULL,
    problem_id BIGINT,
    title      VARCHAR(200)   NOT NULL,
    language   VARCHAR(32)    NOT NULL,
    code       VARCHAR(100000) NOT NULL,
    created_at TIMESTAMP      NOT NULL,
    updated_at TIMESTAMP      NOT NULL,
    CONSTRAINT fk_saved_code_user    FOREIGN KEY (user_id)    REFERENCES users (id)    ON DELETE CASCADE,
    CONSTRAINT fk_saved_code_problem FOREIGN KEY (problem_id) REFERENCES problems (id) ON DELETE SET NULL
);

CREATE INDEX ix_saved_code_user ON saved_code (user_id, updated_at);

CREATE TABLE execution_history (
    id             BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT          NOT NULL,
    saved_code_id  BIGINT,
    problem_id     BIGINT,
    language       VARCHAR(32)     NOT NULL,
    code           VARCHAR(100000) NOT NULL,
    status         VARCHAR(32)     NOT NULL,
    error_message  VARCHAR(4000),
    total_steps    INTEGER         NOT NULL,
    duration_ms    BIGINT          NOT NULL,
    credits_spent  INTEGER         NOT NULL,
    trace_json     VARCHAR(4000000),
    created_at     TIMESTAMP       NOT NULL,
    CONSTRAINT fk_exec_user       FOREIGN KEY (user_id)       REFERENCES users (id)      ON DELETE CASCADE,
    CONSTRAINT fk_exec_saved_code FOREIGN KEY (saved_code_id) REFERENCES saved_code (id) ON DELETE SET NULL,
    CONSTRAINT fk_exec_problem    FOREIGN KEY (problem_id)    REFERENCES problems (id)   ON DELETE SET NULL
);

CREATE INDEX ix_exec_user_created ON execution_history (user_id, created_at);

CREATE TABLE credit_transactions (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    amount      INTEGER      NOT NULL,
    type        VARCHAR(48)  NOT NULL,
    description VARCHAR(500) NOT NULL,
    balance_after INTEGER    NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_credit_tx_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_credit_tx_user_created ON credit_transactions (user_id, created_at);
