-- Adds the test-case judge: problems can optionally declare a method signature, test cases
-- validate submissions against it, and submissions record the verdict.

ALTER TABLE problems ADD COLUMN class_name VARCHAR(64);
ALTER TABLE problems ADD COLUMN method_name VARCHAR(64);
ALTER TABLE problems ADD COLUMN method_static BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE problems ADD COLUMN return_type VARCHAR(64);

CREATE TABLE problem_parameters (
    problem_id BIGINT       NOT NULL,
    position   INTEGER      NOT NULL,
    param_type VARCHAR(64),
    param_name VARCHAR(64),
    PRIMARY KEY (problem_id, position),
    CONSTRAINT fk_problem_param_problem FOREIGN KEY (problem_id) REFERENCES problems (id) ON DELETE CASCADE
);

CREATE TABLE test_cases (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id      BIGINT        NOT NULL,
    expected_output VARCHAR(2000) NOT NULL,
    is_sample       BOOLEAN       NOT NULL DEFAULT FALSE,
    explanation     VARCHAR(1000),
    display_order   INTEGER       NOT NULL,
    CONSTRAINT fk_testcase_problem FOREIGN KEY (problem_id) REFERENCES problems (id) ON DELETE CASCADE
);

CREATE INDEX ix_testcase_problem ON test_cases (problem_id, display_order);

CREATE TABLE test_case_arguments (
    test_case_id BIGINT       NOT NULL,
    position     INTEGER      NOT NULL,
    arg_value    VARCHAR(2000),
    PRIMARY KEY (test_case_id, position),
    CONSTRAINT fk_testcase_arg_case FOREIGN KEY (test_case_id) REFERENCES test_cases (id) ON DELETE CASCADE
);

CREATE TABLE submissions (
    id            BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT          NOT NULL,
    problem_id    BIGINT          NOT NULL,
    language      VARCHAR(32)     NOT NULL,
    code          VARCHAR(100000) NOT NULL,
    verdict       VARCHAR(32)     NOT NULL,
    passed_count  INTEGER         NOT NULL,
    total_count   INTEGER         NOT NULL,
    error_message VARCHAR(4000),
    duration_ms   BIGINT          NOT NULL,
    created_at    TIMESTAMP       NOT NULL,
    CONSTRAINT fk_submission_user    FOREIGN KEY (user_id)    REFERENCES users (id)    ON DELETE CASCADE,
    CONSTRAINT fk_submission_problem FOREIGN KEY (problem_id) REFERENCES problems (id) ON DELETE CASCADE
);

CREATE INDEX ix_submission_user_problem ON submissions (user_id, problem_id, created_at);
